version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python version 3.11 ..."
      - pyenv global $PYTHON_311_VERSION
      - apt-get update
      - apt-get install -y awscli
      # Fetch PEM file from SSM Parameter Store named "terraform"
      - aws ssm get-parameter --name terraform --with-decryption --query "Parameter.Value" --output text > /opt/terraform.pem
      - chmod 400 /opt/terraform.pem

  pre_build:
    commands:
      - echo "Executing pre_build phase..."
      # Add any pre-build commands here

  build:
    commands:
      # Continue with your existing build commands
      - scp -o StrictHostKeyChecking=no -i /opt/terraform.pem /opt/venkat.txt ubuntu@13.235.71.108:/opt/venkat.txt
      - aws s3 cp /opt/venkat.txt s3://personnel01venky01/

  post_build:
    commands:
      - echo "Executing post_build phase..."
      # Add any post-build commands here
