version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update
      - apt-get install -y awscli
env:
  variables:
    backup_folder: "/opt/venkat.txt"
    s3_folder: "s3://elasticbeanstalk-us-east-1-508511762335/sss/"

  build:
    commands:
      - aws s3 cp $backup_folder/* $s3_folder


