version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update
      - apt-get install -y awscli
  build:
    commands:
      - aws s3 cp /opt/venkat.txt s3://personnel01venky01/
