version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python version 3.11 ..."
      - pyenv global $PYTHON_311_VERSION
      - apt-get update
      - apt-get install -y awscli

  pre_build:
    commands:
      - echo "Executing pre_build phase..."

  build:
    commands:
      - aws s3 cp s3://personnel01venky01/terraform.pem /opt/terraform.pem
      - chmod 400 /opt/terraform.pem
      - scp -o StrictHostKeyChecking=no -i /opt/terraform.pem ubuntu@65.0.177.227:/opt/venkat.txt /tmp/venkat.txt

  post_build:
    commands:
      - echo "Executing post_build phase..."
